version: '3'
services:
  movies_data:
    image: mysql:8.0
    container_name: centralmovies_docker
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movies_data
    ports:
      - "3306:3306"
  selenium:
    image: selenium/standalone-chrome
    container_name: centralmovies_selenium
    ports:
      - "4444:4444"
    shm_size: '2gb'